version: '3.8'

services:
  django-app:
    build: .
    container_name: django-app
    depends_on:
      - portfolio-mysql
    environment:
      DATABASE_HOST: portfolio-mysql
      DATABASE_NAME: portfolio_db
      DATABASE_USER: root
      DATABASE_PASSWORD: root
    networks:
      - backend
    ports:
      - "8000:8000"

  portfolio-mysql:
    image: mysql:8.0
    container_name: portfolio-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
